site_name: Communify SDK Documentation

pages:
- Getting started: index.md
- Single Sign On (S2O): s2o.md
- Search Engine Optimization (SEO): seo.md
- Email After Purchase (EAP): eap.md

theme: readthedocs